config/routes.rb
Rails.application.routes.draw do
  resources :records




# get "/records" =>"records#index", as: 'records'
# get "/records/new" => "records#new", as: 'new_record'
# get "/records/:id" => "records#show", as: 'record'
# post "/records" => "records#create"
# delete "/records/:id" => "records#destroy", as: 'delete_record_path'
end


# Prefix Verb   URI Pattern                Controller#Action
# record_index GET    /record(.:format)          record#index
#        POST   /record(.:format)          record#create
# new_record GET    /record/new(.:format)      record#new
# edit_record GET    /record/:id/edit(.:format) record#edit
# record GET    /record/:id(.:format)      record#show
#        PATCH  /record/:id(.:format)      record#update
#        PUT    /record/:id(.:format)      record#update
#        DELETE /record/:id(.:format)      record#destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
  @records = Record.all
  end

  def show
    record_id = params[:id]
    @record = Record.find(record_id)
  end

  def new
    @record = Record.new()
  end

  def create
  Record.create(record_params)
  redirect_to('/records')
end

def update
Record.update(params[:id], record_params)
end

def destroy
  record_id = params[:id]
  @record = Record.find(record_id)
  @record.destroy

  redirect_to('/records')
end


private # Everything below is only able to be used in this controller

def record_params
  params.require(:record).permit(:title, :artist, :year, :cover_art, :song_count)

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RocknRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= link_to "Make a New Record", new_record_path %>     <!-- good -->

  <%= yield %>

  </body>
</html>

app/views/records/_form.html.erb
<%= form_for @record do |f| %>
  <span>Title: </span>
  <%= f.text_field :title, required: true %><br>
  <span>Artist: </span>
  <%= f.text_field :artist, required: true %><br>
  <span>Year: </span>
  <%= f.number_field :year, required: true %><br>
  <span>Cover art: </span>
  <%= f.url_field :cover_art, required: true %><br>
  <span>Song count: </span>
  <%= f.number_field :song_count, required: true %><br>
  <%= f.submit %>
<% end %>

app/views/records/_record.html.erb
<% @records.each do |record| %>
  <p>Title: <%= record.title %></p>
  <p>Artist: <%= record.artist %></p>
  <img src="<%= record.cover_art %>">
  <br>
  <button> <%= link_to "Show", record_path(record) %> </button>
  <button> <%= link_to "delete", record, method: :delete, data:{confirm: "Are you sure?"} %> </button>
<% end %>

app/views/records/edit.html.erb
<h1>Editing Person</h1>
<%= render 'form' %>

app/views/records/index.html.erb
<h1>Rock 'n Rails!</h1>
<%= render 'record' %>

app/views/records/new.html.erb
<h1> Add new Person </h1>
<%= render 'form' %>

app/views/records/show.html.erb
<img src="<%= @record.cover_art %>">
<h1><%= @record.title %></h1>
<h2>by <%= @record.artist %></h2>
<p>Year: <%= @record.year %></p>
<p>Song Count: <%= @record.song_count %></p>
<%= link_to "Back", records_path %>